# -*- coding: utf-8 -*-
"""2020-10-06-melvin-jones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WbZYfZSlTUAaVWRmVU7t4I81V_zqnsf5

# "Melvin Jones 5 anos de idade, perfura seu coração com uma tesoura e vive, washington, dc 1925"
> "Década de 1920"

- Toc: false
- Branch: master
- comments: true
- Author: Maurício Júnior
- categories: [ ]
"""

!wget https://raw.githubusercontent.com/awarischool/data-science/master/image-colorizer/deoldify_wrapper.py

from deoldify_wrapper import DeOldify

deo = DeOldify()

deo.colorize('https://i.redd.it/2ex4er39got51.jpg', render_factor=45)

